"""Generic over-approximation runner — author a SOUND over-approximating summary of a heavy Solidity
function, with an autogenerated conformance PROOF, for ANY contract-under-test.

ONE file to edit and run. You provide:

  1. The TARGETS block below — WHICH function(s) to summarize + the GOAL each summary must preserve
     (edit `CUT` + `TARGETS`). The goal is the crux: it's what stops the agent settling on the trivial
     `Phi = true`. Optionally point a target at a helper spec (`model_spec_import`) defining predicates
     Phi uses (e.g. a `definition wellFormed(...)`).
  2. --setup-conf <path> — a trusted setup .conf naming the CUT and its scene (files/solc/packages/links
     + `verify: CUT:SetupSpec.spec`). sources_root + cut are read from it.

The agent then writes Phi (grounding in the CUT source), and the loop proves each `overApprox_<fn>` rule
on the prover, WEAKENING Phi on a counterexample / simplifying on a timeout, until it holds as strong as
the goal allows. On success the installable `<fn>Summary.spec` is written into the sources tree.

Run (from smtool/demo/):
  PYTHONPATH=<AutoProver>:. <AutoProver>/.venv/bin/python run_overapprox.py \
        --setup-conf /path/to/MySetup.conf [--sources /path/to/.certora_sources] \
        [--targets my_targets] [--model sonnet] [--fill-steps 120] [--local] [--out result.txt]
"""
import argparse, asyncio, sys
from pathlib import Path

from smtool.ir import Signature, Param as P
from smtool.overapprox import OverApproxTarget

# ============================================================================================
# EDIT THIS BLOCK for your contract-under-test. (Example: an integer sqrt library function.)
# ============================================================================================
CUT = "MyMathLib"        # the contract NAME == currentContract == the setup conf's `verify:` target


def TARGETS() -> list[OverApproxTarget]:
    return [
        # DEFAULT (auto) mode: no goal — the agent produces the CLOSEST sound over-approximation CVL can
        # express + the prover can discharge (reconstruct f as faithfully as possible, relax at the wall).
        # This is the autosetup use: summarize a prover-hostile fn (assembly / deps / gas-opt) with no
        # property in hand.
        OverApproxTarget(
            cut=CUT,   # stamped from the setup conf by OverApproxProject.of anyway
            sig=Signature(name="sqrt", params=[P("uint256", "x")], returns=["uint256"],
                          mutability="view", visibility="external"),
        ),
        # GOAL-TAILORED (override) mode: set `goal=...` to preserve a SPECIFIC property (only when known).
        # A tag/flag example (bytesN UDVT result), pointing at a helper spec that defines the predicate:
        # OverApproxTarget(
        #     cut=CUT,
        #     sig=Signature(name="computeId", params=[P("Item[]", "items")],
        #                   returns=["Id"], mutability="view"),
        #     goal="the top byte (tag) of the returned Id equals the expected module constant.",
        #     model_spec_import="Phi_id.spec"),
    ]
# ============================================================================================


async def main():
    sys.stdout.reconfigure(line_buffering=True)
    from langchain_anthropic import ChatAnthropic
    from composer.spec.source.source_env import build_basic_source_tools
    from smtool.setup import consume_setup
    from smtool.overapprox_project import OverApproxProject
    from smtool.agent.overapprox_refine import run_overapprox_loop, OverApproxRefineConfig
    from run_agent import MODELS, StreamHandler, build_cvl_tools

    ap = argparse.ArgumentParser(description="Author + prove over-approx summaries for the TARGETS above.")
    ap.add_argument("--setup-conf", required=True, help="trusted setup .conf naming the CUT + scene")
    ap.add_argument("--targets", default=None,
                    help="OPTIONAL module exposing TARGETS()->list[OverApproxTarget] (and optional CUT), "
                         "instead of the in-file block")
    ap.add_argument("--sources", default=None, help="CUT sources root (default: the setup's sources_root)")
    ap.add_argument("--model", default="sonnet", choices=list(MODELS))
    ap.add_argument("--fill-steps", type=int, default=120, help="cap on the agent's tool-call recursion")
    ap.add_argument("--max-verify-calls", type=int, default=6,
                    help="cap on PROVER runs (minutes each) — bounds tightening so it can't loop forever")
    ap.add_argument("--local", action="store_true", help="LocalProverRunner instead of cloud")
    ap.add_argument("--out", default="", help="dump the final Phi/summary/verdict here")
    args = ap.parse_args()

    setup = consume_setup(args.setup_conf)
    sources = args.sources or str(setup.sources_root)
    out_dir = str(Path(setup.sources_root) / "certora")      # write specs into the sources tree

    _targets, _cut = TARGETS, CUT
    if args.targets:
        import importlib
        mod = importlib.import_module(args.targets)
        _targets = mod.TARGETS
        _cut = getattr(mod, "CUT", setup.cut)

    project = OverApproxProject.of(setup.cut, _targets(), setup.setup_spec_import)
    cfg = OverApproxRefineConfig(out_dir=out_dir, setup_conf=setup.conf,
                                 sources_root=str(setup.sources_root), local=args.local)

    llm = ChatAnthropic(model=MODELS[args.model], max_tokens=8000, max_retries=2, timeout=180)
    src_tools = build_basic_source_tools(sources, forbidden_read=r".*\.certora_internal.*") \
        .base_source_tools if sources else ()
    cvl_tools = await build_cvl_tools()

    def _target_line(fn, t):
        return (f"- {fn}: GOAL — {t.goal}" if t.goal else
                f"- {fn}: no specific property — produce the CLOSEST sound over-approximation "
                "(reconstruct as faithfully as CVL allows, relax only at the wall).")
    lines = "\n".join(_target_line(fn, t) for fn, t in project.targets.items())
    task = ("Author a sound over-approximating summary for each target below by writing its predicate "
            "Phi, then prove each overApprox_<fn> conformance rule. Reconstruct-then-relax; finalize "
            f"within the prover-run budget ({args.max_verify_calls}).\n\nTARGETS:\n" + lines)
    print(f"=== overapprox: cut={setup.cut} targets={list(project.targets)} model={args.model} "
          f"prover={'local' if args.local else 'cloud'} verify_budget={args.max_verify_calls} ===")
    transcript = (args.out + ".transcript") if args.out else "overapprox.transcript"
    res = await run_overapprox_loop(project, task, cfg, llm=llm, extra_tools=[*src_tools, *cvl_tools],
                                    thread_id=setup.cut, fill_steps=args.fill_steps,
                                    max_verify_calls=args.max_verify_calls,
                                    callbacks=[StreamHandler()], transcript_path=transcript)

    report = [f"=== cut={setup.cut} targets={list(project.targets)} model={args.model} ===",
              f"=== ALL VERIFIED === {res.success}   verified targets: {res.verified}",
              "=== conformance ===",
              *(f"    [{'PASS' if r.success else 'FAIL'}] {Path(c).name}" +
                ("" if r.success else "  " + ", ".join(f"{v.rule}:{v.status}" for v in r.failures()))
                for c, r in res.results.items())]
    for fn in project.targets:
        report += [f"\n=== Phi[{fn}] ===\n{project.render_phi(fn)}",
                   f"=== summary[{fn}] {'(INSTALLABLE — verified)' if fn in project.verified else '(NOT verified)'} ===\n"
                   + project.render_summary(fn)]
    text = "\n".join(report)
    print("\n" + text)
    if args.out:
        Path(args.out).write_text(text)
        print(f"\n=== dumped to {args.out} ===")


if __name__ == "__main__":
    asyncio.run(main())
