"""What the CVLR API producer emits, over real rustdoc output rather than a live cargo.

``tests/data/cvlr_rustdoc/`` holds four trimmed payloads from a real
``cargo +nightly rustdoc --output-format json`` run against the pinned reference set: the asserts
crate (macros, including the ones generated by ``impl_bin_assert!``), the mathint crate (a type
whose useful surface is inherent methods), the ``cvlr`` facade (whose whole job is re-exports),
and the derive crate (two procedural macros, which rustdoc addresses unlike everything else).
They are trimmed, not synthesized — a hand-written payload would encode what the author believes
the schema is, which is the thing most likely to be wrong.

The producer is the half of this work that has never been testable: it used to live in another
repository, behind an API key. See ``docs/cvlr-api-docs-plan.md`` §4.2.
"""

import json
from pathlib import Path

import pytest

from composer.rag.import_format import ManualBlockKind
from composer.scripts.cvlr_api_docs import (
    FORMAT_VERSION,
    CrateDocs,
    Item,
    LocalCheckout,
    RustdocUnavailable,
    _leaves,
    _probe_crate,
    build_manifest,
    cvlr_packages,
    items_of,
    manifest_source,
    render_type,
    resolve_aliases,
)
from composer.tools.cvlr_api_rag import API_ROOT, SURFACE_HEADING

_DATA = Path(__file__).parent / "data" / "cvlr_rustdoc"

_CRATES = {
    "cvlr-asserts": ("cvlr_asserts", "0.6.1"),
    "cvlr-mathint": ("cvlr_mathint", "0.6.1"),
    "cvlr": ("cvlr", "0.6.1"),
    "cvlr-derive": ("cvlr_derive", "0.6.1"),
}


def _docs(name: str) -> CrateDocs:
    module, version = _CRATES[name]
    return CrateDocs(
        name=name, version=version, payload=json.loads((_DATA / f"{module}.json").read_text())
    )


@pytest.fixture
def family() -> list[CrateDocs]:
    crates = [_docs(n) for n in _CRATES]
    resolve_aliases(crates)
    return crates


def _named(items, name):
    return next((i for i in items if i.name == name), None)


# ---------------------------------------------------------------------------------------------
# the walk


def test_a_macro_carries_its_matchers_and_not_its_body():
    """The contract, not the implementation.

    rustdoc elides a macro's body as ``{ ... }`` and hands over the matchers, which is the call
    signature and the whole of what a caller needs. An expansion in a corpus the author treats as
    authoritative would invite a dependency on a binding name that is nobody's promise
    (``docs/cvlr-api-docs-plan.md`` §4.2).
    """
    item = _named(items_of(_docs("cvlr-asserts")), "cvlr_assert_le")
    assert item is not None
    assert item.signature.startswith("macro_rules! cvlr_assert_le")
    assert "$lhs:expr" in item.signature and "$rhs:expr" in item.signature
    assert "{ ... }" in item.signature, "the body must stay elided"
    assert "__cvlr_lhs" not in item.signature, "no expansion internals"


def test_a_macro_generated_macro_is_an_item_like_any_other():
    # cvlr_assert_le is produced by impl_bin_assert!, so it has no source line of its own. If
    # rustdoc did not surface it, documenting the template upstream could not reach the corpus
    # either, and the whole macro surface would be unreachable.
    names = {i.name for i in items_of(_docs("cvlr-asserts"))}
    assert {"cvlr_assert_le", "cvlr_assume", "cvlr_satisfy"} <= names


def test_an_inherent_method_is_emitted_under_its_type():
    """``NativeIntU64::u64_max`` has no entry in rustdoc's ``paths`` — it lives inside an impl.

    It was also the single most-searched name in the live run's tool census, so a walk that only
    took path-addressable items would miss the most-wanted item in the corpus.
    """
    item = _named(items_of(_docs("cvlr-mathint")), "NativeIntU64::u64_max")
    assert item is not None
    assert item.signature == "fn u64_max() -> Self"
    assert item.crate == "cvlr-mathint"


def test_a_re_export_names_the_crate_that_defines_it(family):
    """``cvlr::is_u128`` is reached through the facade and defined in ``cvlr-mathint``.

    The entry is filed under the defining crate and *names* the alias, rather than existing twice
    or only under the facade — an agent handed only the facade finds a re-export and stops.
    """
    assert _named(items_of(_docs("cvlr")), "is_u128") is None, (
        "a re-export is not an item of the facade"
    )
    mathint = next(c for c in family if c.name == "cvlr-mathint")
    assert mathint.aliases["cvlr_mathint::nativeint_u64::is_u128"] == ["cvlr::is_u128"]


def test_a_glob_re_export_is_not_claimed_as_a_path(family):
    """``cvlr`` pulls its asserts in with ``pub use super::asserts::*``.

    A glob names no item, so there is no path to report. Inventing one — ``cvlr::cvlr_assume`` —
    would be a guess about what the glob brought into scope, and a path that does not resolve is
    worse than no path at all.
    """
    asserts = next(c for c in family if c.name == "cvlr-asserts")
    assert asserts.aliases == {}
    assert all(not i.aliases for i in items_of(asserts))


def test_an_alias_reaches_the_entry_body(family):
    # The alias is only useful if it is searchable text: `cvlr_api_lookup` runs a keyword search
    # over section content, so an alias recorded but not rendered would not answer "what is
    # cvlr::is_u128?".
    mathint = next(c for c in family if c.name == "cvlr-mathint")
    item = _named(items_of(mathint), "is_u128")
    assert item is not None and item.aliases == ("cvlr::is_u128",)
    body = "\n".join(text for _kind, text in item.body())
    assert "Also reachable as `cvlr::is_u128`." in body


def test_trait_impl_methods_are_not_entries_of_their_own():
    """Twenty ``Add``/``Sub``/``Mul`` impls would be twenty entries nobody searches for.

    The collapse is a rule over the item kind, not a judgement about ideas — which is what lets
    this producer make it without a model.
    """
    names = {i.name for i in items_of(_docs("cvlr-mathint"))}
    assert not any("::add" in n or "::mul" in n for n in names), sorted(names)


def test_the_local_crate_is_the_only_one_documented():
    # A rustdoc payload carries every dependency's items too. Attributing those here would file
    # the same item under several crates, and a reader could not tell which pin governs it.
    assert {i.crate for i in items_of(_docs("cvlr-asserts"))} == {"cvlr-asserts"}


# ---------------------------------------------------------------------------------------------
# type rendering


@pytest.mark.parametrize(
    "node, expected",
    [
        ({"primitive": "u64"}, "u64"),
        ({"generic": "Self"}, "Self"),
        ({"resolved_path": {"path": "Pubkey", "args": None}}, "Pubkey"),
        ({"borrowed_ref": {"lifetime": "'a", "is_mutable": True, "type": {"primitive": "u8"}}},
         "&'a mut u8"),
        ({"slice": {"primitive": "u8"}}, "[u8]"),
        ({"array": {"type": {"primitive": "u8"}, "len": "32"}}, "[u8; 32]"),
        ({"tuple": []}, "()"),
        ({"tuple": [{"primitive": "u8"}, {"primitive": "bool"}]}, "(u8, bool)"),
        ({"raw_pointer": {"is_mutable": False, "type": {"primitive": "u8"}}}, "*const u8"),
    ],
)
def test_types_render_as_rust(node, expected):
    assert render_type(node) == expected


def test_an_unmodelled_type_elides_rather_than_guessing():
    # The caller is about to write this into Rust that has to compile, so a shape this does not
    # model becomes `_` rather than something plausible and wrong.
    assert render_type({"some_future_kind": {"whatever": 1}}) == "_"
    assert render_type(None) == "_"


# ---------------------------------------------------------------------------------------------
# the manifest


def test_the_surface_section_lists_exactly_what_the_walk_emitted(family):
    """Completeness stops being a gate and becomes a property of one extraction.

    The old producer reconciled a regex item scan against a model's output; here the list a caller
    reads and the list the walk produced are the same list, and this is what says so.
    """
    manifest = build_manifest(family, source="test")
    for crate in family:
        items = items_of(crate)
        headers = [API_ROOT, crate.name, crate.version, SURFACE_HEADING]
        section = next(s for s in manifest.manual_sections if list(s.headers) == headers)
        body = "\n".join(b.body for b in section.blocks)
        for item in items:
            assert f"`{item.name}`" in body, f"{item.name} missing from {crate.name}'s surface"
        assert f"{len(items)} items" in body


def test_every_item_is_addressable_by_its_own_header_path(family):
    # `cvlr_api_lookup` fetches a section by its header path, so an item the manual product did
    # not file under its own name could only ever be reached by vector search.
    manifest = build_manifest(family, source="test")
    filed = {tuple(s.headers) for s in manifest.manual_sections}
    for crate in family:
        for item in items_of(crate):
            assert (API_ROOT, crate.name, crate.version, item.name) in filed


def test_the_signature_is_code_and_the_prose_is_not(family):
    # The importer holds code aside behind a <code-ref-N> placeholder so it stays out of the
    # keyword-searchable text. A signature mis-tagged as prose would pollute every keyword hit.
    manifest = build_manifest(family, source="test")
    section = next(
        s for s in manifest.manual_sections if s.headers[-1] == "cvlr_assert_le"
    )
    code = [b for b in section.blocks if b.kind is ManualBlockKind.CODE]
    assert len(code) == 1 and code[0].body.startswith("macro_rules!")


def test_the_version_is_in_every_header_path(family):
    # One version is in the corpus at a time (the pin, §2), so this is provenance rather than a
    # retrieval axis — it is what makes a stale corpus visible in every answer.
    manifest = build_manifest(family, source="test")
    versions = {c.version for c in family}
    for section in manifest.manual_sections:
        assert section.headers[0] == API_ROOT
        assert section.headers[2] in versions


def test_an_unexpected_format_version_is_refused_rather_than_half_parsed():
    """rustdoc JSON is nightly-only and explicitly unstable, so this break will happen.

    A walk that skipped every item it no longer recognized would emit a thin corpus that looks
    like a successful build, and nothing downstream could tell the difference.
    """
    payload = json.loads((_DATA / "cvlr_asserts.json").read_text())
    payload["format_version"] = FORMAT_VERSION + 1
    with pytest.raises(RustdocUnavailable, match="format_version"):
        CrateDocs(name="cvlr-asserts", version="0.6.1", payload=payload)


# ---------------------------------------------------------------------------------------------
# the undocumented report


def test_the_report_lists_exactly_the_items_with_no_prose(family):
    """The corpus can only carry what the crates carry, and this is the ask against them.

    It has to be a list of *items*, not of doc-comment lines: what an agent hits is a specific
    name with nothing behind it, and the person fixing it needs that name.
    """
    from composer.scripts.cvlr_api_docs import undocumented_report

    report = undocumented_report(family)
    for crate in family:
        for item in items_of(crate):
            listed = f"`{item.name}`" in report
            assert listed is (not item.docs), f"{item.name} documented={bool(item.docs)}"


def test_the_report_counts_what_it_lists(family):
    # The counts are the measure of whether the ask is being met, so they cannot drift from the
    # list under them.
    from composer.scripts.cvlr_api_docs import undocumented_report

    report = undocumented_report(family)
    total = sum(len(items_of(c)) for c in family)
    missing = sum(1 for c in family for i in items_of(c) if not i.docs)
    assert f"{missing} of {total} items carry no prose documentation." in report


def test_the_report_carries_the_signature_of_each_missing_item(family):
    # Whoever writes the doc comment needs to see what they are documenting without opening the
    # crate; a bare name would send them looking for it.
    from composer.scripts.cvlr_api_docs import undocumented_report

    report = undocumented_report(family)
    item = _named(items_of(_docs("cvlr-asserts")), "cvlr_assert_le")
    assert item is not None and not item.docs
    assert item.signature.splitlines()[0] in report


# ---------------------------------------------------------------------------------------------
# header paths have to be unique
#
# The manual product keys on the header parts (``parts_unique`` in the importer's schema), and a
# crate exporting a macro and the function it expands into is ordinary CVLR: ``cvlr-log`` does it,
# ``cvlr-spec`` does it four times, and ``cvlr-solana-stake`` exports two functions of one name.
# Before this, those entries shadowed each other and the ingest died at the database with a
# constraint error naming no item at all.


def _item(name: str, kind: str, path: str) -> Item:
    return Item(name=name, kind=kind, crate="cvlr-log", path=path, signature=f"{kind} {name}")


def test_one_name_for_two_items_is_told_apart_by_kind():
    # Which is the distinction in every real case: the macro and the function it expands into.
    leaves = _leaves([
        _item("cvlr_log", "macro", "cvlr_log::cvlr_log"),
        _item("cvlr_log", "function", "cvlr_log::log::cvlr_log"),
    ])
    assert leaves == ["cvlr_log (macro)", "cvlr_log (function)"]


def test_one_name_and_one_kind_fall_back_to_the_defining_path():
    # ``cvlr-solana-stake`` exports `get_minimum_delegation` twice, both functions.
    leaves = _leaves([
        _item("get_minimum_delegation", "function", "cvlr_solana_stake::get_minimum_delegation"),
        _item("get_minimum_delegation", "function", "cvlr_solana_stake::tools::get_minimum_delegation"),
    ])
    assert leaves == [
        "cvlr_solana_stake::get_minimum_delegation",
        "cvlr_solana_stake::tools::get_minimum_delegation",
    ]


def test_a_name_that_is_already_unique_is_left_alone(family):
    """Almost every entry, and the reason the qualifier is not applied uniformly.

    An agent reaches these sections by searching for a bare identifier; putting a parenthesis in
    the middle of every header in the corpus to accommodate seven collisions would make the common
    case read worse to buy nothing.
    """
    for crate in family:
        items = items_of(crate)
        assert _leaves(items) == [i.name for i in items]


def test_no_two_sections_share_a_header_path(family):
    manifest = build_manifest(family, source="test")
    headers = [tuple(s.headers) for s in manifest.manual_sections]
    assert len(set(headers)) == len(headers)


def test_indistinguishable_items_are_refused_rather_than_dropped():
    # Same name, same kind, same path: there is nothing left to key on, and silently keeping one
    # of the two is the outcome nobody could detect.
    with pytest.raises(RustdocUnavailable, match="overwrite each other"):
        _leaves([_item("x", "function", "p::x"), _item("x", "function", "p::x")])


# ---------------------------------------------------------------------------------------------
# documenting a local checkout


def _checkout(name: str) -> LocalCheckout:
    root = Path("/home/eric/src/cvlr")
    return LocalCheckout(root=root, crate_dir=root / name, revision="cvlr-v0.6.1-3-g8d9d463-dirty")


def test_a_checkout_enters_as_a_patch_and_not_as_a_dependency(tmp_path):
    """Which is what keeps the pin and the source apart.

    A path *dependency* would let a checkout decide the version too, and a corpus describing a
    release this build does not support is exactly what the pin exists to prevent. As a patch, a
    checkout that has moved off the pin fails at cargo instead.
    """
    from composer.spec.cvlr_reference import SOLANA

    _probe_crate(tmp_path, SOLANA, {"cvlr-asserts": _checkout("cvlr-asserts")})
    manifest = (tmp_path / "Cargo.toml").read_text()
    deps, patch = manifest.split("[patch.crates-io]")
    assert 'cvlr = "=0.6.1"' in deps
    assert "path" not in deps
    assert 'cvlr-asserts = { path = "/home/eric/src/cvlr/cvlr-asserts" }' in patch


def test_a_probe_with_no_checkouts_has_no_patch_table(tmp_path):
    from composer.spec.cvlr_reference import SOLANA

    _probe_crate(tmp_path, SOLANA, {})
    assert "[patch" not in (tmp_path / "Cargo.toml").read_text()


def test_a_checkout_that_defines_no_cvlr_crate_is_refused(tmp_path):
    """The one failure a caller cannot see: the build finishes, describing the published releases.

    It is the same argument as :meth:`ChainReference.withholding`'s — a setting whose only effect
    is "changed nothing" is indistinguishable from one that worked.
    """
    metadata = {"packages": [{"name": "solana-program", "manifest_path": "/x/Cargo.toml"}]}
    with pytest.raises(RustdocUnavailable, match="defines no CVLR crate"):
        cvlr_packages(metadata, tmp_path)


def test_a_package_resolves_to_its_own_directory_not_the_workspace_root():
    # What `[patch]` has to name. A workspace root would patch in the wrong crate, or nothing.
    metadata = {
        "packages": [
            {"name": "cvlr-asserts", "manifest_path": "/home/eric/src/cvlr/cvlr-asserts/Cargo.toml"},
            {"name": "serde", "manifest_path": "/elsewhere/Cargo.toml"},
        ]
    }
    found = cvlr_packages(metadata, Path("/home/eric/src/cvlr"))
    assert found == {"cvlr-asserts": Path("/home/eric/src/cvlr/cvlr-asserts")}


def test_a_checkout_corpus_is_indistinguishable_from_a_published_one():
    """The rows must not mention where they came from, and this is the reason.

    A checkout is documented in order to be *tried*: to watch an author agent work against
    documentation that is still in review. An entry stamped with a caveat no released corpus
    carries would mean the run under observation was not the run that ships, and the difference
    would show up as a difference in the agent's behaviour rather than as anything visible here.

    Provenance is recorded where no agent reads it — the manifest's source line and the log.
    """
    payload = json.loads((_DATA / "cvlr_asserts.json").read_text())
    published = build_manifest([CrateDocs("cvlr-asserts", "0.6.1", payload)], source="s")
    checkout = build_manifest(
        [CrateDocs("cvlr-asserts", "0.6.1", payload, origin=_checkout("cvlr-asserts"))], source="s"
    )
    assert checkout == published
    assert "/home/eric/src" not in checkout.model_dump_json()


def test_the_manifest_source_names_every_checkout_it_read():
    """What someone looking at an ingested corpus and wondering why it disagrees with crates.io has.

    Grouped by checkout rather than listed per crate: fifteen crates from two trees is two facts.
    It is also the only durable trace, since the rows carry none.
    """
    from composer.spec.cvlr_reference import SOLANA

    assert "checkout" not in manifest_source(SOLANA, {})
    source = manifest_source(
        SOLANA, {"cvlr-asserts": _checkout("cvlr-asserts"), "cvlr-log": _checkout("cvlr-log")}
    )
    assert "cvlr 0.6.1" in source
    assert source.count("/home/eric/src/cvlr @ cvlr-v0.6.1-3-g8d9d463-dirty") == 1
    assert "cvlr-asserts, cvlr-log" in source


def test_the_undocumented_report_records_that_it_measured_a_checkout():
    # The list is meant to shrink, and it shrinks in a checkout first. A report that did not say
    # which tree it counted would read as a measurement of the published crates.
    from composer.scripts.cvlr_api_docs import undocumented_report

    docs = CrateDocs(
        "cvlr-asserts", "0.6.1", json.loads((_DATA / "cvlr_asserts.json").read_text()),
        origin=_checkout("cvlr-asserts"),
    )
    report = undocumented_report([docs])
    assert "local checkouts" in report
    assert "/home/eric/src/cvlr @ cvlr-v0.6.1-3-g8d9d463-dirty" in report


# ---------------------------------------------------------------------------------------------
# procedural macros


def test_a_proc_macro_crate_is_not_an_empty_crate():
    """rustdoc addresses a proc macro's export under an id unrelated to the item's own.

    The usual ``paths[item_id]`` lookup therefore found nothing, the walk read that as "associated
    item, handled elsewhere", and ``cvlr-derive`` came out empty — while its surface section
    announced itself as the complete, closed listing of a crate that exports nothing.
    """
    items = items_of(_docs("cvlr-derive"))
    assert {i.name for i in items} == {"Nondet", "CvlrLog"}
    assert all(i.crate == "cvlr-derive" for i in items)
    assert all(i.path.startswith("cvlr_derive::") for i in items)


def test_a_derive_is_written_as_a_derive_and_not_as_a_bang():
    # `#[derive(Nondet)]` against `Nondet!` is the difference between compiling and not, and
    # rustdoc's `index` calls all three flavours of procedural macro the same thing.
    item = _named(items_of(_docs("cvlr-derive")), "Nondet")
    assert item is not None
    assert item.signature == "#[derive(Nondet)]"
    assert item.kind == "proc_derive"
