"""What the CVLR API producer emits, over real rustdoc output rather than a live cargo.

``tests/data/cvlr_rustdoc/`` holds three trimmed payloads from a real
``cargo +nightly rustdoc --output-format json`` run against the pinned reference set: the asserts
crate (macros, including the ones generated by ``impl_bin_assert!``), the mathint crate (a type
whose useful surface is inherent methods), and the ``cvlr`` facade (whose whole job is re-exports).
They are trimmed, not synthesized — a hand-written payload would encode what the author believes
the schema is, which is the thing most likely to be wrong.

The producer is the half of this work that has never been testable: it used to live in another
repository, behind an API key. See ``docs/cvlr-api-docs-plan.md`` §4.2.
"""

import json
from pathlib import Path

import pytest

from composer.rag.import_format import ManualBlockKind
from composer.scripts.cvlr_api_docs import (
    FORMAT_VERSION,
    CrateDocs,
    RustdocUnavailable,
    build_manifest,
    items_of,
    render_type,
    resolve_aliases,
)
from composer.tools.cvlr_api_rag import API_ROOT, SURFACE_HEADING

_DATA = Path(__file__).parent / "data" / "cvlr_rustdoc"

_CRATES = {
    "cvlr-asserts": ("cvlr_asserts", "0.6.1"),
    "cvlr-mathint": ("cvlr_mathint", "0.6.1"),
    "cvlr": ("cvlr", "0.6.1"),
}


def _docs(name: str) -> CrateDocs:
    module, version = _CRATES[name]
    return CrateDocs(
        name=name, version=version, payload=json.loads((_DATA / f"{module}.json").read_text())
    )


@pytest.fixture
def family() -> list[CrateDocs]:
    crates = [_docs(n) for n in _CRATES]
    resolve_aliases(crates)
    return crates


def _named(items, name):
    return next((i for i in items if i.name == name), None)


# ---------------------------------------------------------------------------------------------
# the walk


def test_a_macro_carries_its_matchers_and_not_its_body():
    """The contract, not the implementation.

    rustdoc elides a macro's body as ``{ ... }`` and hands over the matchers, which is the call
    signature and the whole of what a caller needs. An expansion in a corpus the author treats as
    authoritative would invite a dependency on a binding name that is nobody's promise
    (``docs/cvlr-api-docs-plan.md`` §4.2).
    """
    item = _named(items_of(_docs("cvlr-asserts")), "cvlr_assert_le")
    assert item is not None
    assert item.signature.startswith("macro_rules! cvlr_assert_le")
    assert "$lhs:expr" in item.signature and "$rhs:expr" in item.signature
    assert "{ ... }" in item.signature, "the body must stay elided"
    assert "__cvlr_lhs" not in item.signature, "no expansion internals"


def test_a_macro_generated_macro_is_an_item_like_any_other():
    # cvlr_assert_le is produced by impl_bin_assert!, so it has no source line of its own. If
    # rustdoc did not surface it, documenting the template upstream could not reach the corpus
    # either, and the whole macro surface would be unreachable.
    names = {i.name for i in items_of(_docs("cvlr-asserts"))}
    assert {"cvlr_assert_le", "cvlr_assume", "cvlr_satisfy"} <= names


def test_an_inherent_method_is_emitted_under_its_type():
    """``NativeIntU64::u64_max`` has no entry in rustdoc's ``paths`` — it lives inside an impl.

    It was also the single most-searched name in the live run's tool census, so a walk that only
    took path-addressable items would miss the most-wanted item in the corpus.
    """
    item = _named(items_of(_docs("cvlr-mathint")), "NativeIntU64::u64_max")
    assert item is not None
    assert item.signature == "fn u64_max() -> Self"
    assert item.crate == "cvlr-mathint"


def test_a_re_export_names_the_crate_that_defines_it(family):
    """``cvlr::is_u128`` is reached through the facade and defined in ``cvlr-mathint``.

    The entry is filed under the defining crate and *names* the alias, rather than existing twice
    or only under the facade — an agent handed only the facade finds a re-export and stops.
    """
    assert _named(items_of(_docs("cvlr")), "is_u128") is None, (
        "a re-export is not an item of the facade"
    )
    mathint = next(c for c in family if c.name == "cvlr-mathint")
    assert mathint.aliases["cvlr_mathint::nativeint_u64::is_u128"] == ["cvlr::is_u128"]


def test_a_glob_re_export_is_not_claimed_as_a_path(family):
    """``cvlr`` pulls its asserts in with ``pub use super::asserts::*``.

    A glob names no item, so there is no path to report. Inventing one — ``cvlr::cvlr_assume`` —
    would be a guess about what the glob brought into scope, and a path that does not resolve is
    worse than no path at all.
    """
    asserts = next(c for c in family if c.name == "cvlr-asserts")
    assert asserts.aliases == {}
    assert all(not i.aliases for i in items_of(asserts))


def test_an_alias_reaches_the_entry_body(family):
    # The alias is only useful if it is searchable text: `cvlr_api_lookup` runs a keyword search
    # over section content, so an alias recorded but not rendered would not answer "what is
    # cvlr::is_u128?".
    mathint = next(c for c in family if c.name == "cvlr-mathint")
    item = _named(items_of(mathint), "is_u128")
    assert item is not None and item.aliases == ("cvlr::is_u128",)
    body = "\n".join(text for _kind, text in item.body())
    assert "Also reachable as `cvlr::is_u128`." in body


def test_trait_impl_methods_are_not_entries_of_their_own():
    """Twenty ``Add``/``Sub``/``Mul`` impls would be twenty entries nobody searches for.

    The collapse is a rule over the item kind, not a judgement about ideas — which is what lets
    this producer make it without a model.
    """
    names = {i.name for i in items_of(_docs("cvlr-mathint"))}
    assert not any("::add" in n or "::mul" in n for n in names), sorted(names)


def test_the_local_crate_is_the_only_one_documented():
    # A rustdoc payload carries every dependency's items too. Attributing those here would file
    # the same item under several crates, and a reader could not tell which pin governs it.
    assert {i.crate for i in items_of(_docs("cvlr-asserts"))} == {"cvlr-asserts"}


# ---------------------------------------------------------------------------------------------
# type rendering


@pytest.mark.parametrize(
    "node, expected",
    [
        ({"primitive": "u64"}, "u64"),
        ({"generic": "Self"}, "Self"),
        ({"resolved_path": {"path": "Pubkey", "args": None}}, "Pubkey"),
        ({"borrowed_ref": {"lifetime": "'a", "is_mutable": True, "type": {"primitive": "u8"}}},
         "&'a mut u8"),
        ({"slice": {"primitive": "u8"}}, "[u8]"),
        ({"array": {"type": {"primitive": "u8"}, "len": "32"}}, "[u8; 32]"),
        ({"tuple": []}, "()"),
        ({"tuple": [{"primitive": "u8"}, {"primitive": "bool"}]}, "(u8, bool)"),
        ({"raw_pointer": {"is_mutable": False, "type": {"primitive": "u8"}}}, "*const u8"),
    ],
)
def test_types_render_as_rust(node, expected):
    assert render_type(node) == expected


def test_an_unmodelled_type_elides_rather_than_guessing():
    # The caller is about to write this into Rust that has to compile, so a shape this does not
    # model becomes `_` rather than something plausible and wrong.
    assert render_type({"some_future_kind": {"whatever": 1}}) == "_"
    assert render_type(None) == "_"


# ---------------------------------------------------------------------------------------------
# the manifest


def test_the_surface_section_lists_exactly_what_the_walk_emitted(family):
    """Completeness stops being a gate and becomes a property of one extraction.

    The old producer reconciled a regex item scan against a model's output; here the list a caller
    reads and the list the walk produced are the same list, and this is what says so.
    """
    manifest = build_manifest(family, source="test")
    for crate in family:
        items = items_of(crate)
        headers = [API_ROOT, crate.name, crate.version, SURFACE_HEADING]
        section = next(s for s in manifest.manual_sections if list(s.headers) == headers)
        body = "\n".join(b.body for b in section.blocks)
        for item in items:
            assert f"`{item.name}`" in body, f"{item.name} missing from {crate.name}'s surface"
        assert f"{len(items)} items" in body


def test_every_item_is_addressable_by_its_own_header_path(family):
    # `cvlr_api_lookup` fetches a section by its header path, so an item the manual product did
    # not file under its own name could only ever be reached by vector search.
    manifest = build_manifest(family, source="test")
    filed = {tuple(s.headers) for s in manifest.manual_sections}
    for crate in family:
        for item in items_of(crate):
            assert (API_ROOT, crate.name, crate.version, item.name) in filed


def test_the_signature_is_code_and_the_prose_is_not(family):
    # The importer holds code aside behind a <code-ref-N> placeholder so it stays out of the
    # keyword-searchable text. A signature mis-tagged as prose would pollute every keyword hit.
    manifest = build_manifest(family, source="test")
    section = next(
        s for s in manifest.manual_sections if s.headers[-1] == "cvlr_assert_le"
    )
    code = [b for b in section.blocks if b.kind is ManualBlockKind.CODE]
    assert len(code) == 1 and code[0].body.startswith("macro_rules!")


def test_the_version_is_in_every_header_path(family):
    # One version is in the corpus at a time (the pin, §2), so this is provenance rather than a
    # retrieval axis — it is what makes a stale corpus visible in every answer.
    manifest = build_manifest(family, source="test")
    versions = {c.version for c in family}
    for section in manifest.manual_sections:
        assert section.headers[0] == API_ROOT
        assert section.headers[2] in versions


def test_an_unexpected_format_version_is_refused_rather_than_half_parsed():
    """rustdoc JSON is nightly-only and explicitly unstable, so this break will happen.

    A walk that skipped every item it no longer recognized would emit a thin corpus that looks
    like a successful build, and nothing downstream could tell the difference.
    """
    payload = json.loads((_DATA / "cvlr_asserts.json").read_text())
    payload["format_version"] = FORMAT_VERSION + 1
    with pytest.raises(RustdocUnavailable, match="format_version"):
        CrateDocs(name="cvlr-asserts", version="0.6.1", payload=payload)
