"""Path helpers for the autosetup output layout.

Each helper takes a `project_root` and returns a fully-qualified `Path` for
one well-known artifact. User-facing artifacts live under `certora/`;
intermediate machinery lives under `.certora_internal/`.
"""

import json
from pathlib import Path

from certora_autosetup.utils.constants import (
    CERTORA_REPORTS_DIR,
    DIR_CERTORA_INTERNAL,
    DIR_INTERNAL_CONFS,
    DIR_INTERNAL_DIFFICULT_RETRY,
    DIR_INTERNAL_MULTI_ASSERT,
    DIR_INTERNAL_ROUND_SUMMARIES,
    DIR_INTERNAL_SPECS,
    DIR_INTERNAL_TYPECHECKER_ROUNDS,
    DIR_USER_CERTORA,
    DIR_USER_CONFS,
    DIR_USER_HARNESSES,
    DIR_USER_SPECS,
    FILE_AUTOSETUP_RESULT,
    FILE_COMPILATION_CONF,
    FILE_COMPILATION_DUMMY_SPEC,
    FILE_ERC7201_SPEC,
    FILE_LLM_USAGE,
    FILE_PROVER_USAGE,
    SUMMARIES_SUBDIR,
)


def user_conf_path(project_root: Path, contract: str) -> Path:
    return project_root / DIR_USER_CONFS / f"{contract}.conf"


def user_sanity_spec_path(project_root: Path, contract: str) -> Path:
    """User-facing entry-point spec at certora/specs/sanity-{contract}.spec.

    Generated by autosetup with the bundled rule sanity body and direct imports
    of the summary aggregator, call-resolution, and (when applicable) erc7201 specs.
    Skip-if-exists after first run so user-added rules survive re-runs."""
    return project_root / DIR_USER_SPECS / f"sanity-{contract}.spec"


def user_call_resolution_spec_path(project_root: Path, contract: str) -> Path:
    """Auto-generated call-resolution / linking spec under certora/specs/summaries/."""
    return project_root / DIR_USER_CERTORA / SUMMARIES_SUBDIR / f"{contract}_call_resolution.spec"


def user_erc7201_spec_path(project_root: Path) -> Path:
    return project_root / DIR_USER_SPECS / FILE_ERC7201_SPEC


def user_harnesses_dir(project_root: Path) -> Path:
    """Directory where autosetup writes generated harness contracts.
    """
    return project_root / DIR_USER_HARNESSES


def user_harness_path(project_root: Path, harness_name: str) -> Path:
    """Path of a single generated harness file under ``certora/harnesses/``.
    ``harness_name`` is the contract name (without ``.sol``)
    """
    return user_harnesses_dir(project_root) / f"{harness_name}.sol"


def internal_warmup_spec(project_root: Path, contract: str) -> Path:
    return project_root / DIR_INTERNAL_SPECS / f"warmup-{contract}.spec"


def internal_compilation_conf(project_root: Path) -> Path:
    return project_root / DIR_INTERNAL_CONFS / FILE_COMPILATION_CONF


def internal_compilation_dummy_spec(project_root: Path) -> Path:
    return project_root / DIR_INTERNAL_SPECS / FILE_COMPILATION_DUMMY_SPEC


def internal_test_compilation_conf(project_root: Path, contract: str) -> Path:
    return project_root / DIR_INTERNAL_CONFS / f"test_compilation-{contract}.conf"


def internal_typechecker_round_dir(project_root: Path) -> Path:
    return project_root / DIR_INTERNAL_TYPECHECKER_ROUNDS


def internal_round_summaries_dir(project_root: Path) -> Path:
    return project_root / DIR_INTERNAL_ROUND_SUMMARIES


def internal_multi_assert_dir(project_root: Path) -> Path:
    return project_root / DIR_INTERNAL_MULTI_ASSERT


def internal_difficult_retry_dir(project_root: Path) -> Path:
    return project_root / DIR_INTERNAL_DIFFICULT_RETRY


def _resolve_autosetup_reports_file(project_root: Path, filename: str) -> Path | None:
    """Locate ``filename`` in the reports dir the most recent autosetup run wrote under
    ``project_root``.

    Primary: read ``orchestration_timestamp`` from ``autosetup_result.json`` and build
    ``<CERTORA_REPORTS_DIR>/<ts>/<filename>`` — the deterministic inverse of how the CLI names
    that dir. Fallback (a ``--reports-dir`` override that kept the convention, or an older run): the
    newest timestamped subdir holding ``<filename>``. Timestamps are ``%Y%m%d_%H%M%S``, so a
    plain lexicographic max picks the most recent. Returns ``None`` if nothing is found.

    This is the single source of truth for the on-disk usage-file layout; external consumers (e.g.
    composer) should call the typed wrappers below rather than re-deriving these paths.
    """
    reports_root = project_root / CERTORA_REPORTS_DIR

    result_path = project_root / DIR_CERTORA_INTERNAL / FILE_AUTOSETUP_RESULT
    try:
        timestamp = json.loads(result_path.read_text()).get("orchestration_timestamp")
    except (OSError, ValueError):
        timestamp = None
    if timestamp:
        candidate = reports_root / timestamp / filename
        if candidate.exists():
            return candidate

    try:
        subdirs = sorted((d for d in reports_root.iterdir() if d.is_dir()), key=lambda d: d.name)
    except OSError:
        return None
    for d in reversed(subdirs):
        candidate = d / filename
        if candidate.exists():
            return candidate
    return None


def resolve_autosetup_llm_usage_file(project_root: Path) -> Path | None:
    """Locate the ``llm_usage.json`` the most recent autosetup run wrote under ``project_root``
    (``None`` if absent). See :func:`_resolve_autosetup_reports_file`."""
    return _resolve_autosetup_reports_file(project_root, FILE_LLM_USAGE)


def resolve_autosetup_prover_usage_file(project_root: Path) -> Path | None:
    """Locate the ``prover_usage.json`` the most recent autosetup run wrote under ``project_root``
    (``None`` if absent). See :func:`_resolve_autosetup_reports_file`."""
    return _resolve_autosetup_reports_file(project_root, FILE_PROVER_USAGE)


def strip_sources_anchor(path: str) -> tuple[str, ...]:
    """Path components after a ``.certora_sources`` component, if there is one.

    certoraRun copies the project into an instrumented tree under ``.certora_sources``,
    so the same file is reported with and without that prefix depending on which side
    of the copy reported it.
    """
    parts = Path(path).parts
    if ".certora_sources" in parts:
        i = len(parts) - 1 - parts[::-1].index(".certora_sources")
        return parts[i + 1:]
    return parts


def same_source_file(candidate: str, wanted: str) -> bool:
    """Whether two build-reported paths name the same source file.

    The build mixes project-relative and absolute paths for the same file depending on
    how it was reached, so equality is decided on the longest common suffix of path
    components, after dropping any instrumented-tree prefix.
    """
    if not candidate or not wanted:
        return False
    cand_parts = strip_sources_anchor(candidate)
    want_parts = strip_sources_anchor(wanted)
    depth = min(len(cand_parts), len(want_parts))
    return cand_parts[-depth:] == want_parts[-depth:]
