#!/usr/bin/env python3
"""Generated by composer.cargo.wasm — do not edit.

certoraSorobanProver runs this as its `build_script` and reads the build manifest from stdout. The
command, its confinement wrapper and the manifest were fixed when AutoProver ran the same build as
its pre-submission gate, so this rerun is a warm cargo no-op.
"""

import json
import pathlib
import subprocess
import sys

command = json.loads(pathlib.Path(__file__).with_name('confined_build.json').read_text())
argv = [*command["argv_prefix"], *command["argv"]]

# --cargo_features is how the prover adds features; --json and -l need no handling.
extra = sys.argv[sys.argv.index("--cargo_features") + 1:] if "--cargo_features" in sys.argv else []
if extra:
    argv += ["--features", " ".join(extra)]
# After the features: everything past `--` goes to rustc, not cargo.
argv += ["--", *command["rustc_args"]]

result = subprocess.run(argv, capture_output=True, text=True, cwd=command["cwd"])
sys.stderr.write(result.stderr)

manifest = dict(command["manifest"])
manifest["success"] = result.returncode == 0
print(json.dumps(manifest, indent=2))
sys.exit(result.returncode)
